spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: book-manager
          uri: lb://book-manager # netflix eureka correspondent service
          predicates:
            - Path=/book-manager/** # how we will map the url to the target service
eureka:
  instance:
    prefer-ip-address: ${preferIp:true}
  client:
    register-with-eureka: ${registerWithEureka:true}
    fetch-registry: ${fetchRegistry:true}
    service-url:
      defaultZone: ${deafultZone:http://172.31.17.185:8761/eureka}
    region: ${region:us-east-1}
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include=*: