spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: ${locator:true}
          lower-case-service-id: ${lowerCase:true}
eureka:
  instance:
    prefer-ip-address: ${preferIp:true}
  client:
    register-with-eureka: ${registerWithEureka:true}
    fetch-registry: ${fetchRegistry:true}
    service-url:
      defaultZone: ${defaultZone:http://localhost:8761/eureka}
    region: ${region:us-east-1}
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'